package de.pecus.api.error;

/**
 * Enumeracion para manejo de errores.
 * 
 * @author Luis Enrique Sanchez Santiago
 */
public final class PersonaBusinessErrors {

	private PersonaBusinessErrors() {
		// No debe instanciarse
	}
	
	public static final String MIN_SIZE_DESCRIPCION_ERROR =  "MIN_SIZE_DESCRIPCION_ERROR" ;

	public static final String MIN_SIZE_ID_NOMBRE =  "MIN_SIZE_ID_NOMBRE" ;

	public static final String REQUIRED_ID_NOMBRE_ERROR = "REQUIRED_ID_NOMBRE_ERROR";

	public static final String REQUIRED_DESCRIPCION_ERROR = "REQUIRED_DESCRIPCION_ERROR";

	public static final String REQUIRED_TIPO_IDENTIFICACION_ERROR = "REQUIRED_TIPO_IDENTIFICACION_ERROR";

	public static final String REQUIRED_ID_ERROR = "REQUIRED_ID_ERROR";

	public static final String NOT_FOUND_TIPO_IDENTIFICACION_ERROR = "NOT_FOUND_TIPO_IDENTIFICACION_ERROR";

	public static final String DUPLICATED_TIPO_IDENTIFICACION_ERROR = "DUPLICATED_TIPO_IDENTIFICACION_ERROR";
	
	public static final String REQUIRED_TIPO_MASCOTA_ERROR = "REQUIRED_TIPO_MASCOTA_ERROR";

	public static final String NOT_FOUND_TIPO_MASCOTA_ERROR = "NOT_FOUND_TIPO_MASCOTA_ERROR";

	public static final String DUPLICATED_TIPO_MASCOTA_ERROR = "DUPLICATED_TIPO_MASCOTA_ERROR";
	
	public static final String REQUIRED_TIPO_PARENTESCO_ERROR = "REQUIRED_TIPO_PARENTESCO_ERROR";

	public static final String NOT_FOUND_TIPO_PARENTESCO_ERROR = "NOT_FOUND_TIPO_PARENTESCO_ERROR";

	public static final String DUPLICATED_TIPO_PARENTESCO_ERROR = "DUPLICATED_TIPO_PARENTESCO_ERROR";
	
	public static final String REQUIRED_TIPO_VEHICULO_ERROR = "REQUIRED_TIPO_VEHICULO_ERROR";

	public static final String NOT_FOUND_TIPO_VEHICULO_ERROR = "NOT_FOUND_TIPO_VEHICULO_ERROR";

	public static final String DUPLICATED_TIPO_VEHICULO_ERROR = "DUPLICATED_TIPO_VEHICULO_ERROR";
	
	public static final String REQUIRED_TIPO_PERSONA_ERROR = "REQUIRED_TIPO_PERSONA_ERROR";

	public static final String NOT_FOUND_TIPO_PERSONA_ERROR = "NOT_FOUND_TIPO_PERSONA_ERROR";
	
	public static final String NOT_FOUND_TIPO_EMPRESA_ERROR = "NOT_FOUND_TIPO_EMPRESA_ERROR";

	public static final String DUPLICATED_TIPO_PERSONA_ERROR = "DUPLICATED_TIPO_PERSONA_ERROR";
	
	public static final String REQUIRED_PERSONA_ERROR = "REQUIRED_PERSONA_ERROR";

	public static final String NOT_FOUND_PERSONA_ERROR = "NOT_FOUND_PERSONA_ERROR";

	public static final String DUPLICATED_PERSONA_ERROR = "DUPLICATED_PERSONA_ERROR";

	public static final String REQUIRED_APELLIDO_MAT_ERROR = "REQUIRED_APELLIDO_MAT_ERROR";
	
	public static final String REQUIRED_APELLIDO_PAT_ERROR = "REQUIRED_APELLIDO_PAT_ERROR";
	
	public static final String REQUIRED_USUARIO_ERROR_2 = "REQUIRED_USUARIO_ERROR_2";
	
	public static final String REQUIRED_EMPRESA_ERROR = "REQUIRED_EMPRESA_ERROR";
	
	public static final String REQUIRED_TIPO_RELACION_UNIDAD_PERSONA_ERROR =  "REQUIRED_TIPO_RELACION_UNIDAD_PERSONA_ERROR" ;
	
	public static final String DUPLICATED_TIPO_RELACION_UNIDAD_PERSONA_ERROR =  "DUPLICATED_TIPO_RELACION_UNIDAD_PERSONA_ERROR" ;
	
	public static final String NOT_FOUND_TIPO_RELACION_UNIDAD_PERSONA_ERROR =  "NOT_FOUND_TIPO_RELACION_UNIDAD_PERSONA_ERROR" ;
	
	public static final String REQUIRED_PRIVACIDAD_ERROR = "REQUIRED_PRIVACIDAD_ERROR";
	
	public static final String REQUIRED_REGION_ERROR = "REQUIRED_REGION_ERROR";
	
	public static final String REQUIRED_NUMERO_ERROR = "REQUIRED_NUMERO_ERROR";
	
	public static final String INCOMPLETE_PARAMETERS_ERROR = "INCOMPLETE_PARAMETERS_ERROR";
	
	public static final String INVALID_DATE_FORMAT = "INVALID_DATE_FORMAT";
	
	public static final String USO_CFDI_BAD_VALUE = "USO_CFDI_BAD_VALUE";
	
	//Errores RelUsuarios
	public static final String REQUIRED_PADRE_ERROR = "REQUIRED_PADRE_ERROR";

	public static final String REQUIRED_HIJO_ERROR = "REQUIRED_HIJO_ERROR";

	public static final String NOT_FOUND_REL_USUARIOS_ERROR = "NOT_FOUND_REL_USUARIOS_ERROR";
	
	//Errors RelUnidadPersona
	public static final String NOT_FOUND_REL_UNIDAD_PERSONA_ERROR = "NOT_FOUND_REL_UNIDAD_PERSONA_ERROR";

	public static final String REQUIRED_TIPO_REL_UNIDAD_PERSONA_ERROR = "REQUIRED_TIPO_REL_UNIDAD_PERSONA_ERROR";
	
	public static final String FOUND_REL_UNIDAD_PERSONA_ERROR = "FOUND_REL_UNIDAD_PERSONA_ERROR";
	
	public static final String PERSONAL_ASOCIADO = "PERSONAL_ASOCIADO";

	public static final String REQUIRED_UNIDAD_ERROR = "REQUIRED_UNIDAD_ERROR";
	
	public static final String DUPLICATED_PRINCIPAL = "DUPLICATED_PRINCIPAL";
	
	public static final String NOT_FOUND_SUBTIPO_REL_UNIDAD_PERSONA_ERROR = "NOT_FOUND_SUBTIPO_REL_UNIDAD_PERSONA_ERROR";

	public static final String REQUIRED_SUBTIPO_REL_UNIDAD_PERSONA_ERROR = "REQUIRED_SUBTIPO_REL_UNIDAD_PERSONA_ERROR";
	
	public static final String DUPLICATED_SUBTIPO_REL_UNIDAD_PERSONA_ERROR = "DUPLICATED_SUBTIPO_REL_UNIDAD_PERSONA_ERROR";
	
	//Errors RelUnidadVehiculo
	public static final String NOT_FOUND_REL_UNIDAD_VEHICULO_ERROR = "NOT_FOUND_REL_UNIDAD_VEHICULO_ERROR";

	public static final String REQUIRED_VEHICULO_ERROR = "REQUIRED_VEHICULO_ERROR";

	//Errores de Vehiculo
	public static final String NOT_FOUND_VEHICULO_ERROR = "NOT_FOUND_VEHICULO_ERROR";

	public static final String REQUIRED_MARCA_ERROR = "REQUIRED_MARCA_ERROR";
	
	public static final String REQUIRED_MODELO_ERROR = "REQUIRED_MODELO_ERROR";

	public static final String REQUIRED_SUBMARCA_ERROR = "REQUIRED_SUBMARCA_ERROR";

	public static final String REQUIRED_COLOR_ERROR = "REQUIRED_COLOR_ERROR";

	public static final String REQUIRED_MATRICULADO_EN_ERROR = "REQUIRED_MATRICULADO_EN_ERROR";

	public static final String REQUIRED_MATRICULA_ERROR = "REQUIRED_MATRICULA_ERROR";

	public static final String REQUIRED_ANIO_ERROR = "REQUIRED_ANIO_ERROR";

	
	public static final String MIN_SIZE_MARCA_ERROR = "MIN_SIZE_MARCA_ERROR";

	public static final String MIN_SIZE_MODELO_ERROR = "MIN_SIZE_MODELO_ERROR";

	public static final String MIN_SIZE_SUBMARCA_ERROR = "MIN_SIZE_SUBMARCA_ERROR";

	public static final String MIN_SIZE_COLOR_ERROR = "MIN_SIZE_COLOR_ERROR";

	public static final String MIN_SIZE_MATRICULADO_EN_ERROR = "MIN_SIZE_MATRICULADO_EN_ERROR";

	public static final String MIN_SIZE_MATRICULA_ERROR = "MIN_SIZE_MATRICULA_ERROR";

	//Errores de Mascota

	public static final String NOT_FOUND_MASCOTA_ERROR = "NOT_FOUND_MASCOTA_ERROR";
	
	public static final String NOT_FOUND_UNIDAD = "NOT_FOUND_UNIDAD";
	
	public static final String MIN_SIZE_RAZA_ERROR = "MIN_SIZE_RAZA_ERROR";
	
	public static final String MIN_SIZE_OBSERVACIONES_ERROR = "MIN_SIZE_OBSERVACIONES_ERROR";

	
	public static final String REQUIRED_NAMEIDIOMA_ERROR =  "REQUIRED_NAMEIDIOMA_ERROR" ;

	public static final String NOT_FOUND_IDIOMA_ERROR =  "NOT_FOUND_IDIOMA_ERROR" ;
	
	public static final String REQUIRED_NOMBRE_ERROR =  "REQUIRED_NOMBRE_ERROR" ;
	
	public static final String REQUIRED_DISPONIBILIDAD_ERROR =  "REQUIRED_DISPONIBILIDAD_ERROR" ;
	
	public static final String ID_MASCOTA_EMPTY_ERROR =  "ID_MASCOTA_EMPTY_ERROR" ;
	
	public static final String NOT_FOUND_EMPLEADO_ERROR =  "NOT_FOUND_EMPLEADO_ERROR" ;
	
	// Errores Empresa
	public static final String NOT_FOUND_EMPRESA_ERROR =  "NOT_FOUND_EMPRESA_ERROR" ;
	
	public static final String REQUIRED_AREA_EMPRESA_ERROR =  "REQUIRED_AREA_EMPRESA_ERROR" ;
	
	public static final String NOT_FOUND_AREA_EMPRESA_ERROR =  "NOT_FOUND_AREA_EMPRESA_ERROR" ;

	public static final String NOT_FOUND_PERSONAS_UNIDAD = "NOT_FOUND_PERSONAS_UNIDAD";
	
	public static final String DUPLICATED_RELACION_UNIDAD_PERSONA_ERROR = "DUPLICATED_RELACION_UNIDAD";
	
	public static final String REQUIRED_ID_TIPO_VEHICULO = "REQUIRED_ID_TIPO_VEHICULO";

	public static final String BUSINESS_ERROR_CATEGORIA_CON_VEHICULOS = "BUSINESS_ERROR_CATEGORIA_CON_VEHICULOS";
	
	public static final String REQUIRED_ID_CATEGORIA_VEHICULO = "REQUIRED_ID_CATEGORIA_VEHICULO";
	
	public static final String BUSINESS_ERROR_SUB_CATEGORIA_CON_VEHICULOS = "BUSINESS_ERROR_SUB_CATEGORIA_CON_VEHICULOS";
	
	public static final String BUSINESS_ERROR_MASCOTA_UNIDAD_EXISTE = "BUSINESS_ERROR_MASCOTA_UNIDAD_EXISTE";
	
	public static final String BUSINESS_ERROR_MASCOTA_UNIDAD_NO_EXISTE = "BUSINESS_ERROR_MASCOTA_UNIDAD_NO_EXISTE";
	
	public static final String NOT_FOUND_MASCOTA_UNIDAD_ERROR = "NOT_FOUND_MASCOTA_UNIDAD_ERROR";
	
	public static final String BUSINESS_ERROR_VEHICULO_UNIDAD_EXISTE = "BUSINESS_ERROR_VEHICULO_UNIDAD_EXISTE";
	
	public static final String BUSINESS_ERROR_VEHICULO_UNIDAD_NO_EXISTE = "BUSINESS_ERROR_VEHICULO_UNIDAD_NO_EXISTE";
	
	public static final String NOT_FOUND_VEHICULO_UNIDAD_ERROR = "NOT_FOUND_VEHICULO_UNIDAD_ERROR";
	
	public static final String NOT_FOUND_VEHICULO_PERSONA_LIST_ERROR = "NOT_FOUND_VEHICULO_PERSONA_LIST_ERROR";
	
	public static final String NOT_FOUND_MASCOTA_PERSONA_LIST_ERROR = "NOT_FOUND_MASCOTA_PERSONA_LIST_ERROR";
	

	public static final String NOT_FOUND_LISTA_CATEGORIA_VEHICULO_ERROR = "NOT_FOUND_LISTA_CATEGORIA_VEHICULO_ERROR";

	public static final String NOT_FOUND_CATEGORIA_VEHICULO_ERROR = "NOT_FOUND_CATEGORIA_VEHICULO_ERROR";

	public static final String REQUIRED_CATEGORIA_VEHICULO_ID = "REQUIRED_CATEGORIA_VEHICULO_ID";

	public static final String DUPLICATED_CATEGORIA_VEHICULO_ERROR = "DUPLICATED_CATEGORIA_VEHICULO_ERROR";

	public static final String NOT_FOUND_LISTA_SUBCATEGORIA_VEHICULO_ERROR = "NOT_FOUND_LISTA_SUBCATEGORIA_VEHICULO_ERROR";

	public static final String NOT_FOUND_SUBCATEGORIA_VEHICULO_ERROR = "NOT_FOUND_SUBCATEGORIA_VEHICULO_ERROR";

	public static final String DUPLICATED_SUBCATEGORIA_VEHICULO_ERROR = "DUPLICATED_SUBCATEGORIA_VEHICULO_ERROR";

	public static final String REQUIRED_SUBCATEGORIA_VEHICULO_ID_ERROR = "REQUIRED_SUBCATEGORIA_VEHICULO_ID_ERROR";
	
	public static final String REQUIRED_DESCRIPCION_MARCA_VEHICULO = "REQUIRED_DESCRIPCION_MARCA_VEHICULO";
	
	public static final String BUSINESS_ERROR_PERSONA_UNIDAD_NO_REL = "BUSINESS_ERROR_PERSONA_UNIDAD_NO_REL";
	
	public static final String BUSINESS_ERROR_MATRICULA_EXISTENTE = "BUSINESS_ERROR_MATRICULA_EXISTENTE";
	
	public static final String BUSINESS_ERROR_VEHICULO_RELACION_UNIDAD = "BUSINESS_ERROR_VEHICULO_RELACION_UNIDAD";
	
	public static final String BUSINESS_ERROR_MASCOTA_RELACION_UNIDAD = "BUSINESS_ERROR_MASCOTA_RELACION_UNIDAD";
	
	//Errores plantilla residentes
	public static final String FORMAT_NOMBRE_ERROR = "FORMAT_NOMBRE_ERROR";
	
	public static final String FORMAT_APP_PATERNO_ERROR = "FORMAT_APP_PATERNO_ERROR";
	
	public static final String FORMAT_APP_MATERNO_ERROR = "FORMAT_APP_MATERNO_ERROR";
	
	public static final String REQUIRED_GENERA_USUARIO_ERROR = "REQUIRED_GENERA_USUARIO_ERROR";
	
	public static final String REQUIRED_PAIS_ERROR = "REQUIRED_PAIS_ERROR";
	
	public static final String FORMAT_PAIS_ERROR = "FORMAT_PAIS_ERROR";
	
	public static final String TIPO_REL_UNIDAD_PERSONA_ERROR = "TIPO_REL_UNIDAD_PERSONA_ERROR";
	
	public static final String FORMAT_PRINCIPAL_ERROR = "FORMAT_PRINCIPAL_ERROR";
	
	public static final String FORMAT_EMAIL_ERROR = "FORMAT_EMAIL_ERROR";
	
	public static final String FORMAT_TELEFONO_ERROR = "FORMAT_TELEFONO_ERROR";
	
	public static final String REQUIRED_PAGO_MANTENIMIENTO_ERROR = "REQUIRED_PAGO_MANTENIMIENTO_ERROR";

	public static final String RESIDENTES_WRITE_FILE_RESPONSE_ERROR = "RESIDENTES_WRITE_FILE_RESPONSE_ERROR";
	
	public static final String REQUIRED_ID_PATIENT_AND_ID_PERSON = "REQUIRED_ID_PATIENT_AND_ID_PERSON";
	
	public static final String REQUIRED_BRITHDAY_PERSON = "REQUIRED_BRITHDAY_PERSON";
	public static final String INVALID_BRITHDAY_PERSON = "INVALID_BRITHDAY_PERSON";
	public static final String REQUIRED_GENDER_PERSON = "REQUIRED_GENDER_PERSON";

}
