package de.pecus.api.error;

/**
 * Enumeracion para manejo de errores.
 * 
 * @author Luis Enrique Sanchez Santiago
 */
public final class UsuarioBusinessErrors {

	private UsuarioBusinessErrors() {
		// No debe instanciarse
	}

	public static final String REQUIRED_ID_ERROR = "REQUIRED_ID_ERROR";

	public static final String REQUIRED_DESCRIPCION_ERROR = "REQUIRED_DESCRIPCION_ERROR";

	public static final String REQUIRED_USUARIO_ERROR = "REQUIRED_USUARIO_ERROR";

	public static final String REQUIRED_PASSWORD_ERROR = "REQUIRED_PASSWORD_ERROR";

	public static final String REQUIRED_TOKEN_ERROR = "REQUIRED_TOKEN_ERROR";
	
	public static final String REQUIRED_REFRESH_TOKEN_ERROR = "REQUIRED_REFRESH_TOKEN_ERROR";
	
	public static final String NOT_FOUND_REFRESH_TOKEN_ERROR = "NOT_FOUND_REFRESH_TOKEN_ERROR";

	public static final String LOGIN_FAILED_ERROR = "LOGIN_FAILED_ERROR";

	public static final String INVALID_TOKEN_ERROR = "INVALID_TOKEN_ERROR";

	public static final String EXPIRED_TOKEN_ERROR = "EXPIRED_TOKEN_ERROR";

	public static final String REQUIRED_ID_NOMBRE_ERROR = "REQUIRED_ID_NOMBRE_ERROR";

	public static final String REQUIRED_TIPO_ROL_ERROR = "REQUIRED_TIPO_ROL_ERROR";

	public static final String NOT_FOUND_TIPO_ROL_ERROR = "NOT_FOUND_TIPO_ROL_ERROR";

	public static final String DUPLICATED_TIPO_ROL_ERROR = "DUPLICATED_TIPO_ROL_ERROR";

	public static final String MIN_SIZE_DESCRIPCION_ERROR = "MIN_SIZE_DESCRIPCION_ERROR";

	public static final String MIN_SIZE_ID_NOMBRE_ERROR = "MIN_SIZE_ID_NOMBRE_ERROR";

	public static final String REQUIRED_FUNCION_ERROR = "REQUIRED_FUNCION_ERROR";

	public static final String NOT_FOUND_FUNCION_ERROR = "NOT_FOUND_FUNCION_ERROR";

	public static final String DUPLICATED_FUNCION_ERROR = "DUPLICATED_FUNCION_ERROR";

	public static final String REQUIRED_ROL_ERROR = "REQUIRED_ROL_ERROR";

	public static final String NOT_FOUND_ROL_ERROR = "NOT_FOUND_ROL_ERROR";

	public static final String DUPLICATED_ROL_ERROR = "DUPLICATED_ROL_ERROR";
	
	public static final String REQUIRED_USUARIO_CONDO_ROL_ERROR = "REQUIRED_USUARIO_CONDO_ROL_ERROR";

	public static final String NOT_FOUND_USUARIO_CONDO_ROL_ERROR = "NOT_FOUND_USUARIO_CONDO_ROL_ERROR";
	
	public static final String NOT_FOUND_USUARIO_CONDO_ROL_ERROR_BY_APP = "NOT_FOUND_USUARIO_CONDO_ROL_ERROR_BY_APP";

	public static final String DUPLICATED_USUARIO_CONDO_ROL_ERROR = "DUPLICATED_USUARIO_CONDO_ROL_ERROR";
	
	public static final String REQUIRED_FECHA_INICIO_ERROR = "REQUIRED_FECHA_INICIO_ERROR";
	
	public static final String REQUIRED_FECHA_FIN_ERROR = "REQUIRED_FECHA_FIN_ERROR";
	
	public static final String REQUIRED_RESTRICCION_ERROR = "REQUIRED_RESTRICCION_ERROR";

	public static final String REQUIRED_ROL_FUNCION_ERROR = "REQUIRED_ROL_FUNCION_ERROR";

	public static final String NOT_FOUND_ROL_FUNCION_ERROR = "NOT_FOUND_ROL_FUNCION_ERROR";

	public static final String DUPLICATED_ROL_FUNCION_ERROR = "DUPLICATED_ROL_FUNCION_ERROR";
	
	public static final String NOT_FOUND_USUARIO_ERROR = "NOT_FOUND_USUARIO_ERROR";
	
	public static final String REQUIRED_UNIDAD_ERROR = "REQUIRED_UNIDAD_ERROR";

	public static final String NOT_FOUND_UNIDAD_ERROR = "NOT_FOUND_UNIDAD_ERROR";
	
	public static final String REQUIRED_IS_MOBILE_ERROR = "REQUIRED_IS_MOBILE_ERROR";

	public static final String NOT_FOUND_SUBMENU_ERROR = "NOT_FOUND_SUBMENU_ERROR";
	
	public static final String REQUIRED_SUBMENU_ERROR = "REQUIRED_SUBMENU_ERROR";
	
	public static final String DUPLICATED_SUBMENU_ERROR = "DUPLICATED_SUBMENU_ERROR";
	
	public static final String REQUIRED_MENU_ERROR = "REQUIRED_MENU_ERROR";
	
	public static final String NOT_FOUND_MENU_ERROR = "NOT_FOUND_MENU_ERROR";
	
	public static final String REQUIRED_ROL_FUNCION_MENU_ERROR = "REQUIRED_ROL_FUNCION_MENU_ERROR";
	
	public static final String DUPLICATED_ROL_FUNCION_MENU_ERROR = "DUPLICATED_ROL_FUNCION_MENU_ERROR";
	
	public static final String NOT_FOUND_ROL_FUNCION_MENU_ERROR = "NOT_FOUND_ROL_FUNCION_MENU_ERROR";
	
	public static final String NOT_FOUND_REL_FUNCION_SUBMENU_ERROR = "NOT_FOUND_REL_FUNCION_SUBMENU_ERROR";
	
	public static final String REQUIRED_REL_FUNCION_SUBMENU_ERROR = "REQUIRED_REL_FUNCION_SUBMENU_ERROR";
	
	public static final String DUPLICATED_REL_FUNCION_SUBMENU_ERROR = "DUPLICATED_REL_FUNCION_SUBMENU_ERROR";

	public static final String REQUIRED_PATH_ERROR = "REQUIRED_PATH_ERROR";
	
	public static final String DUPLICATED_MENU_ERROR = "DUPLICATED_MENU_ERROR";
	
	public static final String NOT_FOUND_MENU_IDNOMBRE_ERROR = "NOT_FOUND_MENU_IDNOMBRE_ERROR";
	
	public static final String REQUIRED_I18N_ERROR = "REQUIRED_I18N_ERROR";
	
	public static final String NOT_FOUND_I18N_ERROR = "NOT_FOUND_I18N_ERROR";
	
	public static final String REQUIRED_USER_ID_EMAIL_ERROR = "REQUIRED_USER_ID_EMAIL_ERROR";
	
	public static final String REQUIRED_USER_ID_DEVICE_ERROR = "REQUIRED_USER_ID_DEVICE_ERROR";
	
	public static final String DUPLICATED_USER_ID_EMAIL_ERROR = "DUPLICATED_USER_ID_EMAIL_ERROR";
	
	public static final String DUPLICATED_USER_ID_DEVICE_ERROR = "DUPLICATED_USER_ID_DEVICE_ERROR";
	
	public static final String REQUIRED_NOTIFICATION_ENABLED_ERROR = "REQUIRED_NOTIFICATION_ENABLED_ERROR";
	
	public static final String REQUIRED_NOMBRE_EMPRESA_ERROR = "REQUIRED_NOMBRE_EMPRESA_ERROR";
	
	public static final String REQUIRED_TIPO_EMPRESA_ERROR = "REQUIRED_TIPO_EMPRESA_ERROR";
	
	public static final String REQUIRED_NOMBRE_PERSONA_ERROR = "REQUIRED_NOMBRE_PERSONA_ERROR";
	
	public static final String REQUIRED_APELLIDO_PAT_PERSONA_ERROR = "REQUIRED_APELLIDO_PAT_PERSONA_ERROR";
	
	public static final String REQUIRED_APELLIDO_MAT_PERSONA_ERROR = "REQUIRED_APELLIDO_MAT_PERSONA_ERROR";
	
	public static final String REQUIRED_TIPO_PERSONA_ERROR = "REQUIRED_TIPO_PERSONA_ERROR";
	
	public static final String ROL_ERROR = "ROL_ERROR";
	
	public static final String REQUIRED_EMAIL_OR_PHONE_ERROR = "REQUIRED_EMAIL_OR_PHONE_ERROR";
	
	public static final String REQUIRED_EMAIL_OR_ID_ERROR = "REQUIRED_EMAIL_OR_ID_ERROR";
	
	public static final String PERSON_ALREADY_HAVE_EMPLOYEE = "PERSON_ALREADY_HAVE_EMPLOYEE";
	
	public static final String REQUIRED_ALEXA_CLIENT_ID_ERROR = "REQUIRED_ALEXA_CLIENT_ID_ERROR";
	
	public static final String INVALID_ALEXA_CLIENT_ID_ERROR = "INVALID_ALEXA_CLIENT_ID_ERROR";
	
	public static final String REQUIRED_ALEXA_CODE_ERROR = "REQUIRED_ALEXA_CODE_ERROR";
	
	public static final String REQUIRED_ALEXA_CLIENT_SECRET_ERROR = "REQUIRED_ALEXA_CLIENT_SECRET_ERROR";
	
	public static final String INVALID_ALEXA_CLIENT_SECRET_ERROR = "INVALID_ALEXA_CLIENT_SECRET_ERROR";
	
	public static final String NOT_FOUND_ROL_APLICACION_ERROR = "NOT_FOUND_ROL_APLICACION_ERROR";
	
	public static final String CHANGE_EMAIL_USER_ERROR = "CHANGE_EMAIL_USER_ERROR";
	
	public static final String CHANGE_PHONE_NUMBER_USER_ERROR = "CHANGE_PHONE_NUMBER_USER_ERROR";
	
	public static final String REQUIRED_USER_ID_MOBILE_NUMBER_ERROR = "REQUIRED_USER_ID_MOBILE_NUMBER_ERROR";

	public static final String REQUIRED_LADA_PAIS_ERROR = "REQUIRED_LADA_PAIS_ERROR";

	public static final String INVALID_EMAIL_FORMAT_ERROR = "INVALID_EMAIL_FORMAT_ERROR";

	public static final String DUPLICATED_USER_MOBILE_NUMBER_ERROR = "DUPLICATED_USER_MOBILE_NUMBER_ERROR";

	public static final String NOT_FOUND_TIPO_EMPRESA =  "NOT_FOUND_TIPO_EMPRESA" ;

	public static final String DUPLICATED_NOMBRE_EMPRESA_ERROR =  "DUPLICATED_NOMBRE_EMPRESA_ERROR" ;

	public static final String MIN_SIZE_PASSWORD_ERROR =  "MIN_SIZE_PASSWORD_ERROR" ;
	
	public static final String INACTIVE_PASSWORD_ERROR =  "INACTIVE_PASSWORD_ERROR" ;
	
	// Nuevos errores agregados para el servicio de UsuarioAplicacionRol
	public static final String REQUIRED_APLICACION_ERROR = "REQUIRED_APLICACION_ERROR";
	
	public static final String REQUIRED_ID_USUARIO_FOR_ROL_ERROR = "REQUIRED_ID_USUARIO_FOR_ROL_ERROR";

	public static final String NOT_FOUND_APLCIACION_ERROR = "NOT_FOUND_APLCIACION_ERROR";

	public static final String NOT_FOUND_RESTRICCION_ERROR = "NOT_FOUND_RESTRICCION_ERROR";
	
	public static final String REQUIRED_CODE_ERROR = "REQUIRED_CODE_ERROR";
	
	public static final String REQUIRED_PASSWORD_ACTUAL_ERROR = "REQUIRED_PASSWORD_ACTUAL_ERROR";
	
	public static final String REQUIRED_PASSWORD_NUEVO_ERROR = "REQUIRED_PASSWORD_NUEVO_ERROR";
	
	public static final String PASSWORD_ACTUAL_INCORRECTO_ERROR = "PASSWORD_ACTUAL_INCORRECTO_ERROR";
	
	public static final String BULK_INSERT_USERS_ERROR = "BULK_INSERT_USERS_ERROR";
	
	public static final String NOT_FOUND_USUARIO_NOTIFICACION_ERROR = "NOT_FOUND_USUARIO_NOTIFICACION_ERROR";
	
	public static final String REQUIRED_EMAIL_PHONE_NUMBER_ERROR = "REQUIRED_EMAIL_PHONE_NUMBER_ERROR";
	
	/* Inician errores usados en el envio de notificaciones a usuarios que nunca se han logueado*/
	public static final String NOT_FOUND_USUARIO_NEVER_LOGGED_ERROR = "NOT_FOUND_USUARIO_NEVER_LOGGED_ERROR";
	
	public static final String NOTIFICACION_EXITOSA_A_USUARIOS = "NOTIFICACION_EXITOSA_A_USUARIOS";
	
	public static final String NOTIFICACION_FALLIDA_A_USUARIOS = "NOTIFICACION_FALLIDA_A_USUARIOS";
	/* Terminan errores usados en el envio de notificaciones a usuarios que nunca se han logueado*/
	
	public static final String NOT_FOUND_USUARIO_APLICACION_ERROR = "NOT_FOUND_USUARIO_APLICACION_ERROR";
	
	public static final String USER_ALREADY_REGISTERED_APPLICATION_ERROR = "USER_ALREADY_REGISTERED_APPLICATION_ERROR";
	
	public static final String USER_ALREADY_REGISTERED_OTHER_APPLICATION_ERROR = "USER_ALREADY_REGISTERED_OTHER_APPLICATION_ERROR";
	
	public static final String USER_ALREADY_REGISTERED_BUT_NOT_RELATIONSHIP_APP_ERROR = "USER_ALREADY_REGISTERED_BUT_NOT_RELATIONSHIP_APP_ERROR";
	
	public static final String INCOMPLETE_REGISTRATION_DATA_ERROR = "INCOMPLETE_REGISTRATION_DATA_ERROR";
	
	public static final String EMAIL_VALIDATION_MISSING_ERROR = "EMAIL_VALIDATION_MISSING_ERROR";
	
	public static final String INVALID_EXPIRATION_DATE_FORMAT_ERROR = "INVALID_EXPIRATION_DATE_FORMAT_ERROR";
	
	public static final String USUARIO_NO_CONFIGURADO_EN_APP_ERROR = "USUARIO_NO_CONFIGURADO_EN_APP_ERROR";
	
	public static final String REQUIRED_ID_PATIENT_OR_ID_PERSON = "REQUIRED_ID_PATIENT_OR_ID_PERSON";
	
	public static final String REQUIRED_EMAIL_OR_PHONE = "REQUIRED_EMAIL_OR_PHONE";
	
	public static final String REQUIRED_DOCTOR_ID = "REQUIRED_DOCTOR_ID";
	
	public static final String REQUIRED_ID_ROL_ERROR = "REQUIRED_ID_ROL_ERROR";
	
	public static final String NOT_FOUND_USUARIO_ROL_ERROR = "NOT_FOUND_USUARIO_ROL_ERROR";
	
	public static final String EXIST_USER_ROL_ERROR = "EXIST_USER_ROL_ERROR";
	
	public static final String RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";

    public static final String REQUIRED_CODIGO_ACTIVACION = "REQUIRED_CODIGO_ACTIVACION";

    public static final String INVALID_CODIGO_ACTIVACION = "INVALID_CODIGO_ACTIVACION";

	public static final String EXPIRED_CODIGO_ACTIVACION = "EXPIRED_CODIGO_ACTIVACION";

    public static final String EXCEEDED_INTENTS_CODIGO_ACTIVACION = "EXCEEDED_INTENTS_CODIGO_ACTIVACION";

    public static final String REQUIRED_ID_USUARIO = "REQUIRED_ID_USUARIO";

    public static final String REQUIRED_FIREBASE_TOKEN = "REQUIRED_FIREBASE_TOKEN";

	public static final String REQUIRED_ID_PATIENT = "REQUIRED_ID_PATIENT";

    public static final String REQUIRED_FECHA_NACIMIENTO = "REQUIRED_FECHA_NACIMIENTO";

    public static final String REQUIRED_GENERO = "REQUIRED_GENERO";

    public static final String REQUIRED_EMAIL_ON_USER = "REQUIRED_EMAIL_ON_USER";
	
	public static final String ACTIVATION_CODE_ERROR = "ACTIVATION_CODE_ERROR";
	
	public static final String REQUIRED_CODIGO_ACTIVACION_ERROR = "REQUIRED_CODIGO_ACTIVACION_ERROR";
	
	public static final String REQUIRED_AZURE_APP_SCOPE_ERROR = "REQUIRED_AZURE_APP_SCOPE_ERROR";
	
	public static final String REQUIRED_AZURE_APP_TENANT_DNS_ERROR = "REQUIRED_AZURE_APP_TENANT_DNS_ERROR";
	
	public static final String REQUIRED_AZURE_CLIENT_ID_ERROR = "REQUIRED_AZURE_CLIENT_ID_ERROR";
	
	public static final String REQUIRED_AZURE_CLIENT_SECRET_ERROR = "REQUIRED_AZURE_CLIENT_ID_ERROR";
	
	public static final String SEND_NOTIFICATION_EMAIL_ERROR = "SEND_NOTIFICATION_EMAIL_ERROR";

	public static final String INCRESE_STATISTICS_ERROR = "INCRESE_STATISTICS_ERROR";
	
	public static final String EXIST_PATIENT_ERROR = "EXIST_PATIENT_ERROR";
	
	public static final String EXIST_PERSON_ERROR  = "EXIST_PERSON_ERROR";
	
	public static final String REQUIRED_NOT_FOUND_APPLICATION_ID_ERROR = "REQUIRED_NOT_FOUND_APPLICATION_ID_ERROR";
	
	public static final String REQUIRED_ID_PERSON = "REQUIRED_ID_PERSON";
	
	public static final String REQUIRED_EMAIL = "REQUIRED_EMAIL";
	
	public static final String REQUIRED_PHONE_NUMBER = "REQUIRED_PHONE_NUMBER";
	
	public static final String MIN_SIZE_PHONE_NUMBER = "MIN_SIZE_PHONE_NUMBER";
	
	public static final String REQUIRED_DATA_OF_CONTACT = "REQUIRED_DATA_OF_CONTACT";
	
	public static final String DATA_OF_CONTACT_ERROR = "DATA_OF_CONTACT_ERROR";
	
	public static final String DOCTOR_ID_NOT_MATCH = "DOCTOR_ID_NOT_MATCH";
	
	public static final String NEW_EMAIL_HAVE_ID_DOCTOR = "NEW_EMAIL_HAVE_ID_DOCTOR";
	
	public static final String ADD_ROL_ERROR = "ADD_ROL_ERROR";
	
	public static final String EMAILS_NOT_FOUND_ERROR = "EMAILS_NOT_FOUND_ERROR";
	
	public static final String EMAIL_NOT_IS_PATIENT_ERROR = "EMAIL_NOT_IS_PATIENT_ERROR";
	
	public static final String INVALID_PERSON_ID = "INVALID_PERSON_ID";

    public static final String PATIENT_DATA_NOT_FOUND_ERROR = "PATIENT_DATA_NOT_FOUND_ERROR";

    public static final Object SIMILAR_PERSON_ERROR = "SIMILAR_PERSON_ERROR";

    public static final String DUPLICATED_ID_PATIENT_ERROR = "DUPLICATED_ID_PATIENT_ERROR";

	public static final String PATIENT_NOT_FOUND_ERROR = "PATIENT_NOT_FOUND_ERROR";

	public static final String GENERAL_ERROR_ON_PERSON_CALL = "GENERAL_ERROR_ON_PERSON_CALL";

    public static final Object ALTA_USUARIO_POS_ERROR = "ALTA_USUARIO_POS_ERROR";

    public static final String SEND_NOTIFICATION_SMS_ERROR = "SEND_NOTIFICATION_SMS_ERROR";
}